const buttons=document.querySelectorAll('.lang-btn');const translated=document.querySelectorAll('[data-es][data-en]');const header=document.getElementById('floatingHeader');const hero=document.getElementById('inicio');const transitionSection=document.getElementById('transicion');const heroMedia=document.querySelector('.hero-media');const start=document.getElementById('startJourney');
function applyLanguage(lang){document.documentElement.lang=lang;translated.forEach(el=>el.textContent=el.dataset[lang]);buttons.forEach(btn=>btn.classList.toggle('active',btn.dataset.lang===lang));localStorage.setItem('aura-language',lang)}
buttons.forEach(btn=>btn.addEventListener('click',()=>applyLanguage(btn.dataset.lang)));applyLanguage(localStorage.getItem('aura-language')||'es');
const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}})},{threshold:.14});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
function updateHeader(){header.classList.toggle('visible',window.scrollY>hero.offsetHeight*.72)}
let ticking=false;function updateParallax(){heroMedia.style.transform=`translate3d(0,${window.scrollY*.12}px,0) scale(1.045)`;ticking=false}
window.addEventListener('scroll',()=>{updateHeader();if(!ticking){requestAnimationFrame(updateParallax);ticking=true}},{passive:true});updateHeader();
const polish=document.createElement('style');polish.textContent=`
.hero-cta{transition:background .3s ease,transform .3s ease}.hero-cta:hover{background:rgba(165,183,107,.16);transform:translateY(-2px)}
.journey-manifest{display:flex;align-items:center;justify-content:center;gap:22px;margin:48px auto 0;color:#657044;font-size:.68rem;font-weight:600;letter-spacing:.18em}.journey-manifest i{width:38px;height:1px;background:rgba(101,112,68,.42)}
.transition-cta{display:inline-flex;align-items:center;gap:18px;margin-top:42px;padding-bottom:9px;border-bottom:1px solid rgba(101,112,68,.55);color:#38452d;font-size:.72rem;font-weight:600;letter-spacing:.15em}.transition-cta b{font-size:1rem;animation:auraDown 1.8s infinite}@keyframes auraDown{50%{transform:translateY(5px)}}
.section-lead{max-width:590px;margin:22px auto 0;color:#566154;line-height:1.7}.species-image-wrap a{position:relative;display:block;height:100%;min-height:680px;overflow:hidden}.species-image-wrap a:after{content:"";position:absolute;inset:0;background:linear-gradient(to top,rgba(5,12,8,.55),transparent 42%);opacity:.2;transition:opacity .45s}.species-image-wrap:hover a:after{opacity:.72}.species-image-wrap img{transition:transform 1.2s cubic-bezier(.2,.7,.2,1),filter .6s ease}.species-image-wrap:hover img{filter:saturate(1.05) contrast(1.02)}
.image-explore{position:absolute;z-index:2;left:28px;bottom:26px;padding:10px 13px;border:1px solid rgba(255,255,255,.5);background:rgba(8,16,11,.38);backdrop-filter:blur(8px);color:#fff!important;font-size:.66rem!important;font-weight:600;letter-spacing:.15em;opacity:0;transform:translateY(8px);transition:.4s}.species-image-wrap:hover .image-explore{opacity:1;transform:none}.species-copy>a{padding-bottom:7px;border-bottom:1px solid transparent;transition:.3s}.species-copy>a:hover{border-color:currentColor;transform:translateX(4px)}
.journey-starting .hero-inner{opacity:.15;transform:scale(.985);transition:opacity .58s ease,transform .58s ease}.journey-starting .hero-overlay{background:rgba(5,9,7,.84);transition:background .58s ease}
@media(max-width:980px){.species-image-wrap a{min-height:560px}}
@media(max-width:680px){
.floating-header{min-height:58px}.floating-brand{display:flex;align-items:center}.floating-brand img{width:82px!important;max-height:52px}.language-switcher{gap:6px}.lang-btn{min-width:34px;min-height:34px;font-size:.7rem}
.hero-inner{padding:92px 18px 64px!important}.brand-stage{width:min(280px,82vw)!important;margin-bottom:8px!important}.hero-presenta{font-size:.58rem!important;letter-spacing:.28em!important}.hero h1{font-size:clamp(3.1rem,16.5vw,4.7rem)!important;line-height:.84!important}.hero-tagline{font-size:1.28rem!important;max-width:310px!important;line-height:1.2!important}.hero-cta{min-height:50px;margin-top:24px!important;padding:14px 16px!important;font-size:.68rem!important;letter-spacing:.11em!important}
.transition-section{padding:76px 18px!important}.transition-line{font-size:.78rem!important;letter-spacing:.11em!important}.transition-content h2{font-size:clamp(3rem,15vw,4.6rem)!important}.transition-content>p:not(.transition-line){font-size:.98rem!important;line-height:1.7!important;margin-top:24px!important}.journey-manifest{gap:8px;margin-top:34px;font-size:.56rem;letter-spacing:.08em;flex-wrap:wrap}.journey-manifest i{width:10px}.transition-cta{min-height:44px;align-items:center;font-size:.6rem;margin-top:32px}
.section-heading{padding:74px 18px 52px!important;margin-bottom:0!important}.section-heading h2{font-size:clamp(2.8rem,14vw,4rem)!important}.section-lead{padding:0 6px;font-size:.95rem!important}.species-chapter{padding:56px 16px!important;gap:26px!important}.species-image-wrap,.species-image-wrap a,.species-image-wrap img{min-height:0!important;height:62svh;max-height:520px}.species-image-wrap{border-radius:2px}.species-copy{padding:0 2px!important}.species-copy>span{font-size:.61rem!important;letter-spacing:.13em!important}.species-copy h3{font-size:clamp(2.45rem,13vw,3.5rem)!important;margin-top:10px!important}.species-copy .scientific{margin-bottom:16px!important}.species-copy>p:not(.scientific){font-size:.98rem!important;line-height:1.68!important}.species-copy>a{min-height:44px;display:inline-flex!important;align-items:center;margin-top:12px!important}.image-explore{opacity:1;transform:none;left:14px;bottom:14px;padding:9px 11px;font-size:.58rem!important}
.process-section{padding:76px 18px 88px!important}.process-intro{margin-bottom:48px!important}.process-intro h2{font-size:clamp(2.7rem,13vw,3.9rem)!important}.process-line article{padding-left:44px!important}.purpose-section{min-height:620px!important}.purpose-content{padding:72px 18px!important}.purpose-content blockquote{font-size:clamp(2.1rem,10vw,3.4rem)!important}.footer{padding:46px 18px!important}.footer img{width:150px!important}.social-links{gap:16px!important}.social-links a{min-height:44px;display:inline-flex;align-items:center}
}
@media(max-width:390px){.hero h1{font-size:3rem!important}.journey-manifest{font-size:.52rem}.species-image-wrap,.species-image-wrap a,.species-image-wrap img{height:58svh}.species-copy h3{font-size:2.55rem!important}}
@media(prefers-reduced-motion:reduce){.transition-cta b{animation:none}.journey-starting .hero-inner{opacity:1;transform:none}}
`;document.head.appendChild(polish);
start.addEventListener('click',()=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){transitionSection.scrollIntoView();return}document.body.classList.add('journey-starting');setTimeout(()=>{transitionSection.scrollIntoView({behavior:'smooth'});setTimeout(()=>document.body.classList.remove('journey-starting'),700)},420)});
