const buttons=document.querySelectorAll('.lang-btn');const translated=document.querySelectorAll('[data-es][data-en]');const header=document.getElementById('floatingHeader');const hero=document.getElementById('inicio');const transitionSection=document.getElementById('transicion');const heroMedia=document.querySelector('.hero-media');const start=document.getElementById('startJourney');
function applyLanguage(lang){document.documentElement.lang=lang;translated.forEach(el=>el.textContent=el.dataset[lang]);buttons.forEach(btn=>btn.classList.toggle('active',btn.dataset.lang===lang));localStorage.setItem('aura-language',lang)}
buttons.forEach(btn=>btn.addEventListener('click',()=>applyLanguage(btn.dataset.lang)));applyLanguage(localStorage.getItem('aura-language')||'es');
const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}})},{threshold:.14});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
function updateHeader(){header.classList.toggle('visible',window.scrollY>hero.offsetHeight*.72)}
let ticking=false;function updateParallax(){heroMedia.style.transform=`translate3d(0,${window.scrollY*.12}px,0) scale(1.045)`;ticking=false}
window.addEventListener('scroll',()=>{updateHeader();if(!ticking){requestAnimationFrame(updateParallax);ticking=true}},{passive:true});updateHeader();
const polish=document.createElement('style');polish.textContent=`
.hero-cta{transition:background .3s ease,transform .3s ease}.hero-cta:hover{background:rgba(165,183,107,.16);transform:translateY(-2px)}
.journey-manifest{display:flex;align-items:center;justify-content:center;gap:22px;margin:48px auto 0;color:#657044;font-size:.68rem;font-weight:600;letter-spacing:.18em}.journey-manifest i{width:38px;height:1px;background:rgba(101,112,68,.42)}
.transition-cta{display:inline-flex;align-items:center;gap:18px;margin-top:42px;padding-bottom:9px;border-bottom:1px solid rgba(101,112,68,.55);color:#38452d;font-size:.72rem;font-weight:600;letter-spacing:.15em}.transition-cta b{font-size:1rem;animation:auraDown 1.8s infinite}@keyframes auraDown{50%{transform:translateY(5px)}}
.section-lead{max-width:590px;margin:22px auto 0;color:#566154;line-height:1.7}.species-image-wrap a{position:relative;display:block;height:100%;min-height:680px;overflow:hidden}.species-image-wrap a:after{content:"";position:absolute;inset:0;background:linear-gradient(to top,rgba(5,12,8,.55),transparent 42%);opacity:.2;transition:opacity .45s}.species-image-wrap:hover a:after{opacity:.72}.species-image-wrap img{transition:transform 1.2s cubic-bezier(.2,.7,.2,1),filter .6s ease}.species-image-wrap:hover img{filter:saturate(1.05) contrast(1.02)}
.image-explore{position:absolute;z-index:2;left:28px;bottom:26px;padding:10px 13px;border:1px solid rgba(255,255,255,.5);background:rgba(8,16,11,.38);backdrop-filter:blur(8px);color:#fff!important;font-size:.66rem!important;font-weight:600;letter-spacing:.15em;opacity:0;transform:translateY(8px);transition:.4s}.species-image-wrap:hover .image-explore{opacity:1;transform:none}.species-copy>a{padding-bottom:7px;border-bottom:1px solid transparent;transition:.3s}.species-copy>a:hover{border-color:currentColor;transform:translateX(4px)}
.journey-starting .hero-inner{opacity:.15;transform:scale(.985);transition:opacity .58s ease,transform .58s ease}.journey-starting .hero-overlay{background:rgba(5,9,7,.84);transition:background .58s ease}
@media(max-width:980px){.species-image-wrap a{min-height:560px}}@media(max-width:680px){.journey-manifest{gap:10px;margin-top:38px;font-size:.58rem;letter-spacing:.1em}.journey-manifest i{width:14px}.species-image-wrap a{min-height:460px}.image-explore{opacity:1;transform:none;left:18px;bottom:18px}.section-lead{padding:0 12px}.transition-cta{font-size:.62rem}}
@media(prefers-reduced-motion:reduce){.transition-cta b{animation:none}.journey-starting .hero-inner{opacity:1;transform:none}}
`;document.head.appendChild(polish);
start.addEventListener('click',()=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){transitionSection.scrollIntoView();return}document.body.classList.add('journey-starting');setTimeout(()=>{transitionSection.scrollIntoView({behavior:'smooth'});setTimeout(()=>document.body.classList.remove('journey-starting'),700)},420)});
